### ISSUE TITLE
About TrackingNet training dataset

### ISSUE THREAD

**Issue by ZhouZhang233** [MCG-NJU/FCOT#2]
Did you use the full trackingnet dataset  for training in your code?
And if I want to train your code, do I have to download the 1TB dataset first?

**Comment by yutaocui** [comment]
For fair comparison, we use the same training datasets with DiMP, which including 4 training sequences in TrackingNet dataset (https://github.com/visionml/pytracking/blob/master/ltr/train_settings/dimp/dimp50.py#L34). 
Besides, I modified the TrackingNet-devkit for re-downloading the bad zips which can be found at https://github.com/yutaocui/TrackingNet-devkit-moidfication.

**Comment by ZhouZhang233** [comment]
Thanks for your reply!
Your 4 training chunks including "training_0"、"training_1"、"training_2"、"training_3", right?
It's really difficult to download it without vpn.....

**Comment by yutaocui** [comment]
Yes.
